#!/usr/bin/env python3
"""
Analyze Remediation Classification Results
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from azure_production_pipeline import get_db_connection, release_db_connection, is_db_available

def main():
    if not is_db_available():
        print("❌ Database not available")
        return
    
    conn = get_db_connection()
    cursor = conn.cursor()

    print('=== REMEDIATION CLASSIFICATION BREAKDOWN ===')
    print('(Analysis of 2,376 funders processed in remediation)')
    print()

    # Get classification counts from remediation period
    cursor.execute('''
        SELECT 
            classification_type,
            COUNT(*) as count,
            ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM funders WHERE updated_at >= '2025-12-14 00:00:00'), 2) as percentage
        FROM funders 
        WHERE updated_at >= '2025-12-14 00:00:00'
        GROUP BY classification_type
        ORDER BY count DESC
    ''')

    print('📊 CLASSIFICATION RESULTS:')
    print('-' * 60)
    total_processed = 0
    grantmaking_count = 0
    non_grantmaking_count = 0
    
    for row in cursor.fetchall():
        classification, count, percentage = row
        total_processed += count
        
        if classification == 'GRANTMAKING_CHARITY':
            print(f'✅ {classification}: {count} funders ({percentage}%) - Actual grantmaking trusts')
            grantmaking_count = count
        elif classification == 'OPERATIONAL_CHARITY':
            print(f'🏢 {classification}: {count} funders ({percentage}%) - Direct service providers')
            non_grantmaking_count += count
        elif classification == 'FUNDRAISING_PLATFORM':
            print(f'📢 {classification}: {count} funders ({percentage}%) - Fundraising platforms')
            non_grantmaking_count += count
        elif classification == 'NON_CHARITY':
            print(f'❌ {classification}: {count} funders ({percentage}%) - Not charities')
            non_grantmaking_count += count
        elif classification == 'NO_CONTENT_FOUND':
            print(f'🔍 {classification}: {count} funders ({percentage}%) - No content found')
            non_grantmaking_count += count
        elif classification == 'UNCLASSIFIED':
            print(f'❓ {classification}: {count} funders ({percentage}%) - Classification unclear')
            non_grantmaking_count += count
        else:
            print(f'📝 {classification}: {count} funders ({percentage}%)')
            non_grantmaking_count += count

    print()
    print(f'📈 SUMMARY:')
    print(f'   Total funders processed: {total_processed}')
    print(f'   Actual grantmaking charities: {grantmaking_count} ({grantmaking_count/total_processed*100:.1f}%)')
    print(f'   Non-grantmaking entities: {non_grantmaking_count} ({non_grantmaking_count/total_processed*100:.1f}%)')
    print()

    # Now check how many actually generated opportunities
    cursor.execute('''
        SELECT 
            f.classification_type,
            COUNT(DISTINCT f.id) as funders_with_opps,
            COUNT(o.id) as total_opportunities
        FROM funders f
        LEFT JOIN opportunities o ON f.id = o.funder_id
        WHERE f.updated_at >= '2025-12-14 00:00:00'
        GROUP BY f.classification_type
        ORDER BY funders_with_opps DESC
    ''')

    print('📈 OPPORTUNITIES GENERATED BY CLASSIFICATION:')
    print('-' * 60)
    total_opportunities = 0
    for row in cursor.fetchall():
        classification, funders_with_opps, total_opps = row
        total_opportunities += total_opps
        print(f'{classification}:')
        print(f'  - Funders with opportunities: {funders_with_opps}')
        print(f'  - Total opportunities: {total_opps}')
        print()

    print(f'Total opportunities created: {total_opportunities}')

    cursor.close()
    release_db_connection(conn)

if __name__ == "__main__":
    main()